### ISSUE TITLE
suggest to use http://purl.obolibrary.org/obo/RO_0002440 instead of  [http://purl.obolibrary.org/obo/GO_0051702] and name: [is symbiont of]

### ISSUE THREAD

**Issue by jhpoelen** [arw36/EcoPics_Interactions#1]
hi @arw36 -

Neat to see your EcoPic interactions! Especially the one disputing that Turdus rufiventris eats Euterpe edulis 'cause their beaks are too small ([1], attached from https://www.globalbioticinteractions.org/?accordingTo=globi%3Aarw36%2FEcoPics_Interactions&interactionType=ecologicallyRelatedTo&sourceTaxon=Turdus%20rufiventris&targetTaxon=Euterpe%20edulis ) 

Just noticed some minor review notes via https://github.com/arw36/EcoPics_Interactions/runs/4904159494?check_suite_focus=true

```
Review of [arw36/EcoPics_Interactions] included:
  - 13 interaction(s)
  - 4 note(s)
  - 13 info(s)

[arw36/EcoPics_Interactions] has 4 reviewer note(s):
      2 invalid date string [December 2017]
      2 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/GO_0051702] and name: [is symbiont of]
```
First would be fixed by using ISO8601 format: ```2017-12``` instead of ```December 2017```.
second could be fixed by using http://purl.obolibrary.org/obo/RO_0002440 instead of  [http://purl.obolibrary.org/obo/GO_0051702] and name: [is symbiont of] .

Did you contact contributors/authors of references/source below that appear to contradict your refuted claim as part of their publications? 

[🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=net.long0.tsv) M_SD_001 Provider: [⚙️](https://github.com/globalbioticinteractions/fricke2020) [🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=globi%3Aglobalbioticinteractions%2Ffricke2020)[](https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/fricke2020/README.txt) Fricke, E.C., Svenning, J. Accelerating homogenization of the global plant–frugivore meta-network. Nature 585, 74–78 (2020). https://doi.org/10.1038/s41586-020-2640-y Accessed via <https://github.com/globalbioticinteractions/fricke2020/archive/a104a34d91a6267efdc0660ff45ca7783cfc8b20.zip> at 2022-02-05T19:18:03.845Z. [discuss...](https://github.com/globalbioticinteractions/fricke2020/issues/new?body=Hi%21%0A%0AThanks%20for%20helping%20to%20make%20existing%20biotic%20interaction%20data%20easier%20to%20find%20and%20access%21%0A%0AI%20was%20just%20looking%20at%20your%20GloBI%20indexed%20record%20at%20https%3A%2F%2Fwww.globalbioticinteractions.org%2F%3FaccordingTo%3Dglobi%253Aarw36%252FEcoPics_Interactions%26interactionType%3DecologicallyRelatedTo%26sourceTaxon%3DTurdus%2520rufiventris%26targetTaxon%3DEuterpe%2520edulis%20and%20I%20was%20wondering%20about%20...%20%28please%20add%20your%20own%20text%29&title=your%20indexed%20records%20for%20M_SD_001)
[🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=zip%3Ahttp%3A%2F%2Fbinarystore.wiley.com%2Fstore%2F10.1002%2Fecy.1818%2Fasset%2Fsupinfo%2Fecy1818-sup-0002-DataS1.zip%3Fv%3D1%26s%3Da048d36ea6ae68f2afd0f1491f6b4deacbadcda8!%2FATLANTIC_frugivory.csv) doi:10.1002/ecy.1818 Provider: [⚙️](https://github.com/globalbioticinteractions/bello2017) [🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=globi%3Aglobalbioticinteractions%2Fbello2017)[](https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/bello2017/README.txt) Bello, C., Galetti, M., Montan, D., Pizo, M. A., Mariguela, T. C., Culot, L., Bufalo, F., Labecca, F., Pedrosa, F., Constantini, R., Emer, C., Silva, W. R., da Silva, F. R., Ovaskainen, O. and Jordano, P. (2017), Atlantic frugivory: a plant–frugivore interaction data set for the Atlantic Forest. Ecology, 98: 1729. doi:10.1002/ecy.1818 Accessed via <https://github.com/globalbioticinteractions/bello2017/archive/7718c22ab0d05f9c0c504bbffeac7c404bb3c28b.zip> at 2022-02-05T18:15:46.941Z. [discuss...](https://github.com/globalbioticinteractions/bello2017/issues/new?body=Hi%21%0A%0AThanks%20for%20helping%20to%20make%20existing%20biotic%20interaction%20data%20easier%20to%20find%20and%20access%21%0A%0AI%20was%20just%20looking%20at%20your%20GloBI%20indexed%20record%20at%20https%3A%2F%2Fwww.globalbioticinteractions.org%2F%3FaccordingTo%3Dglobi%253Aarw36%252FEcoPics_Interactions%26interactionType%3DecologicallyRelatedTo%26sourceTaxon%3DTurdus%2520rufiventris%26targetTaxon%3DEuterpe%2520edulis%20and%20I%20was%20wondering%20about%20...%20%28please%20add%20your%20own%20text%29&title=your%20indexed%20records%20for%20doi%3A10.1002%2Fecy.1818)
MAURO GALETTI, ROGER GUEVARA, MARINA C. C�RTES, RODRIGO FADINI, SANDRO VON MATTER, ABRA�O B. LEITE, F�BIO LABECCA, THIAGO RIBEIRO, CAROLINA S. CARVALHO, ROSANE G. COLLEVATTI, MATHIAS M. PIRES, PAULO R. GUIMAR�ES JR., PEDRO H. BRANCALION, MILTON C. RIBEIRO, PEDRO JORDANO. 2013. Functional Extinction of Birds Drives Rapid Evolutionary Changes in Seed Size. Science. Vol. 340, Issue 6136, pp. 1086-1090 Provider: [⚙️](https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics) [🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=globi%3Afgabriel1891%2FPalm-Frugivore_Interactions_Neo-Afrotropics)[](https://depot.globalbioticinteractions.org/reviews/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics/README.txt) Muñoz, G., Trøjelsgaard, K., & W.D. Kissling. 2018. A synthesis of animal-mediated seed dispersal of palms reveals distinct biogeographic differences in species interactions. Journal of Biogeography (in progress) Accessed via <https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics/archive/49f339a3603b19b8a6f602612dc2dfae9c252131.zip> at 2022-02-05T18:11:27.680Z. [discuss...](https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics/issues/new?body=Hi%21%0A%0AThanks%20for%20helping%20to%20make%20existing%20biotic%20interaction%20data%20easier%20to%20find%20and%20access%21%0A%0AI%20was%20just%20looking%20at%20your%20GloBI%20indexed%20record%20at%20https%3A%2F%2Fwww.globalbioticinteractions.org%2F%3FaccordingTo%3Dglobi%253Aarw36%252FEcoPics_Interactions%26interactionType%3DecologicallyRelatedTo%26sourceTaxon%3DTurdus%2520rufiventris%26targetTaxon%3DEuterpe%2520edulis%20and%20I%20was%20wondering%20about%20...%20%28please%20add%20your%20own%20text%29&title=your%20indexed%20records%20for%20%20MAURO%20GALETTI%2C%20ROGER%20GUEVARA%2C%20MARINA%20C.%20C%EF%BF%BDRTES%2C%20RODRIGO%20FADINI%2C%20SANDRO%20VON%20MATTER%2C%20ABRA%EF%BF%BDO%20B.%20LEITE%2C%20F%EF%BF%BDBIO%20LABECCA%2C%20THIAGO%20RIBEIRO%2C%20CAROLINA%20S.%20CARVALHO%2C%20ROSANE%20G.%20COLLEVATTI%2C%20MATHIAS%20M.%20PIRES%2C%20PAULO%20R.%20GUIMAR%EF%BF%BDES%20JR.%2C%20PEDRO%20H.%20BRANCALION%2C%20MILTON%20C.%20RIBEIRO%2C%20PEDRO%20JORDANO.%202013.%20Functional%20Extinction%20of%20Birds%20Drives%20Rapid%20Evolutionary%20Changes%20in%20Seed%20Size.%20Science.%20Vol.%20340%2C%20Issue%206136%2C%20pp.%201086-1090)
Leite, Abraao de Barros; Brancalion, Pedro H. S.; Guevara, Roger; Galetti, Mauro. 2012. Differential seed germination of a keystone palm (Euterpe edulis) dispersed by avian frugivores. Journal of Tropical Ecology. 615-618 Provider: [⚙️](https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics) [🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=globi%3Afgabriel1891%2FPalm-Frugivore_Interactions_Neo-Afrotropics)[](https://depot.globalbioticinteractions.org/reviews/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics/README.txt) Muñoz, G., Trøjelsgaard, K., & W.D. Kissling. 2018. A synthesis of animal-mediated seed dispersal of palms reveals distinct biogeographic differences in species interactions. Journal of Biogeography (in progress) Accessed via <https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics/archive/49f339a3603b19b8a6f602612dc2dfae9c252131.zip> at 2022-02-05T18:11:27.680Z. [discuss...](https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics/issues/new?body=Hi%21%0A%0AThanks%20for%20helping%20to%20make%20existing%20biotic%20interaction%20data%20easier%20to%20find%20and%20access%21%0A%0AI%20was%20just%20looking%20at%20your%20GloBI%20indexed%20record%20at%20https%3A%2F%2Fwww.globalbioticinteractions.org%2F%3FaccordingTo%3Dglobi%253Aarw36%252FEcoPics_Interactions%26interactionType%3DecologicallyRelatedTo%26sourceTaxon%3DTurdus%2520rufiventris%26targetTaxon%3DEuterpe%2520edulis%20and%20I%20was%20wondering%20about%20...%20%28please%20add%20your%20own%20text%29&title=your%20indexed%20records%20for%20Leite%2C%20Abraao%20de%20Barros%3B%20Brancalion%2C%20Pedro%20H.%20S.%3B%20Guevara%2C%20Roger%3B%20Galetti%2C%20Mauro.%202012.%20Differential%20seed%20germination%20of%20a%20keystone%20palm%20%28Euterpe%20edulis%29%20dispersed%20by%20avian%20frugivores.%20Journal%20of%20Tropical%20Ecology.%20615-618)

[1]  Mathias M Pires, Mauro Galetti [Too big to fit](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/fee.2248) Front Ecol Environ 2020; 18( 7): 400– 400, https://doi.org/10.1002/fee.2248

**Comment by arw36** [comment]
I fixed the edits. What is the logic of notifying authors, especially authors of aggregated databases? I think there may be several cases where individuals within species behave in different ways, so support and refutation of an interaction is valid. Since this is just a fun thing I'm putting together on the side, I'm not gonna invest the time to do that.  

If globi has suggestions about contributing beyond datasets, such as communicating to authors/dataset creators, annotating datasets further, etc. I suggest there be a section on the "Contribute" page outline the goals and best practices in additional to new dataset standards of providing a preferred contact (email) for dataset contributors.
